### ISSUE TITLE
GraphQL endpoint

### ISSUE THREAD

**Issue by azzamsa** [thangchung/go-coffeeshop#19]
Hi.

Thanks for creating this awesome &ldquo;boilerplate&rdquo; to learn the best practice.

Is there any plan to add GraphQL endpoint for this?

Thanks! :heart:

**Comment by thangchung** [comment]
Thanks for the feedback, we don't have implementation for GraphQL right now and don't have plans to do that in this repo. But it is easy to do that because we have already implemented it by following Clean Architecture so that you can add the adaptor for GraphQL and then call the usecase components underneath. Feel free to re-open if there is anything else that needs to be discussed.
